name: Test Coverage

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - '**'
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
      - name: Install Node.js packages
        run: npm install
      - name: Run tests
        run: npm run test:coverage
